// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytiplybxzmjupkkxlgsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0aXBseWJ4em1qdXBra3hsZ3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NzE5NDUsImV4cCI6MjA2NzM0Nzk0NX0.Uyfskz91AGbXt0ZusNHxr_Hcr7xY9oKS-VXnR3Lisdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});